local _G = GLOBAL

Assets = 
{
	Asset("ANIM", "anim/hornfire.zip"),
	Asset("IMAGE", "images/hornfire.tex"),
	Asset("ATLAS", "images/hornfire.xml"),
}

PrefabFiles = 
{
	"horn",
	"fireflies",
	"hornfire",
}

local language_strings = GetModConfigData("HORNFIRE_LANGUAGE") ~= nil
                        and _G.require("translate_" .. GetModConfigData("HORNFIRE_LANGUAGE"))
                        or _G.require("translate_english")

_G.STRINGS.NAMES.HORNFIRE = language_strings["HORNFIRE_NAME"]
_G.STRINGS.CHARACTERS.GENERIC.DESCRIBE.HORNFIRE = language_strings["HORNFIRE_CHARACTERS_GENERIC_DESCRIBE"]
_G.STRINGS.CHARACTERS.WILLOW.DESCRIBE.HORNFIRE = language_strings["HORNFIRE_CHARACTERS_WILLOW_DESCRIBE"]
_G.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.HORNFIRE = language_strings["HORNFIRE_CHARACTERS_WOLFGANG_DESCRIBE"]
_G.STRINGS.CHARACTERS.WENDY.DESCRIBE.HORNFIRE = language_strings["HORNFIRE_CHARACTERS_WENDY_DESCRIBE"]
_G.STRINGS.CHARACTERS.WX78.DESCRIBE.HORNFIRE = language_strings["HORNFIRE_CHARACTERS_WX78_DESCRIBE"]
_G.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.HORNFIRE = language_strings["HORNFIRE_CHARACTERS_WICKERBOTTOM_DESCRIBE"]
_G.STRINGS.CHARACTERS.WOODIE.DESCRIBE.HORNFIRE = language_strings["HORNFIRE_CHARACTERS_WOODIE_DESCRIBE"]
_G.STRINGS.CHARACTERS.WAXWELL.DESCRIBE.HORNFIRE = language_strings["HORNFIRE_CHARACTERS_WAXWELL_DESCRIBE"]
_G.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.HORNFIRE = language_strings["HORNFIRE_CHARACTERS_WATHGRITHR_DESCRIBE"]
_G.STRINGS.CHARACTERS.WEBBER.DESCRIBE.HORNFIRE = language_strings["HORNFIRE_CHARACTERS_WEBBER_DESCRIBE"]
_G.STRINGS.CHARACTERS.WINONA.DESCRIBE.HORNFIRE = language_strings["HORNFIRE_CHARACTERS_WINONA_DESCRIBE"]
_G.STRINGS.RECIPE_DESC.HORNFIRE = language_strings["HORNFIRE_RECIPE_DESC"]

local hornfire = Recipe("hornfire", {Ingredient("horn", 1),Ingredient("fireflies", 1),Ingredient("rocks", 3)}, GLOBAL.RECIPETABS.LIGHT, GLOBAL.TECH.SCIENCE_ONE,"hornfire_placer",1)
hornfire.atlas = "images/hornfire.xml"
hornfire.image = "hornfire.tex"